# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/fpermana/repositories/SVGBuild/ui/MainWindow.ui'
#
# Created: Wed Jun  4 20:17:57 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1000, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon64.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.optionsGroupBox = QtGui.QGroupBox(self.centralWidget)
        self.optionsGroupBox.setObjectName(_fromUtf8("optionsGroupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.optionsGroupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.buildGroupBox = QtGui.QGroupBox(self.optionsGroupBox)
        self.buildGroupBox.setObjectName(_fromUtf8("buildGroupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.buildGroupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.buildPathCheckBox = QtGui.QCheckBox(self.buildGroupBox)
        self.buildPathCheckBox.setObjectName(_fromUtf8("buildPathCheckBox"))
        self.verticalLayout.addWidget(self.buildPathCheckBox)
        self.buildTextCheckBox = QtGui.QCheckBox(self.buildGroupBox)
        self.buildTextCheckBox.setObjectName(_fromUtf8("buildTextCheckBox"))
        self.verticalLayout.addWidget(self.buildTextCheckBox)
        self.buildImageCheckBox = QtGui.QCheckBox(self.buildGroupBox)
        self.buildImageCheckBox.setObjectName(_fromUtf8("buildImageCheckBox"))
        self.verticalLayout.addWidget(self.buildImageCheckBox)
        self.gridLayout_2.addWidget(self.buildGroupBox, 0, 0, 1, 1)
        self.rangeGroupBox = QtGui.QGroupBox(self.optionsGroupBox)
        self.rangeGroupBox.setObjectName(_fromUtf8("rangeGroupBox"))
        self.formLayout = QtGui.QFormLayout(self.rangeGroupBox)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.fromLabel = QtGui.QLabel(self.rangeGroupBox)
        self.fromLabel.setObjectName(_fromUtf8("fromLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.fromLabel)
        self.fromSpinBox = QtGui.QSpinBox(self.rangeGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fromSpinBox.sizePolicy().hasHeightForWidth())
        self.fromSpinBox.setSizePolicy(sizePolicy)
        self.fromSpinBox.setMinimum(1)
        self.fromSpinBox.setMaximum(99999)
        self.fromSpinBox.setObjectName(_fromUtf8("fromSpinBox"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.fromSpinBox)
        self.untilLabel = QtGui.QLabel(self.rangeGroupBox)
        self.untilLabel.setObjectName(_fromUtf8("untilLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.untilLabel)
        self.untilSpinBox = QtGui.QSpinBox(self.rangeGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.untilSpinBox.sizePolicy().hasHeightForWidth())
        self.untilSpinBox.setSizePolicy(sizePolicy)
        self.untilSpinBox.setMinimum(1)
        self.untilSpinBox.setMaximum(99999)
        self.untilSpinBox.setProperty("value", 99999)
        self.untilSpinBox.setObjectName(_fromUtf8("untilSpinBox"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.untilSpinBox)
        self.gridLayout_2.addWidget(self.rangeGroupBox, 1, 0, 1, 1)
        self.behaviourGroupBox = QtGui.QGroupBox(self.optionsGroupBox)
        self.behaviourGroupBox.setObjectName(_fromUtf8("behaviourGroupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.behaviourGroupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.pageCheckBox = QtGui.QCheckBox(self.behaviourGroupBox)
        self.pageCheckBox.setObjectName(_fromUtf8("pageCheckBox"))
        self.verticalLayout_2.addWidget(self.pageCheckBox)
        self.cameraCheckBox = QtGui.QCheckBox(self.behaviourGroupBox)
        self.cameraCheckBox.setObjectName(_fromUtf8("cameraCheckBox"))
        self.verticalLayout_2.addWidget(self.cameraCheckBox)
        self.backwardCheckBox = QtGui.QCheckBox(self.behaviourGroupBox)
        self.backwardCheckBox.setObjectName(_fromUtf8("backwardCheckBox"))
        self.verticalLayout_2.addWidget(self.backwardCheckBox)
        self.topCheckBox = QtGui.QCheckBox(self.behaviourGroupBox)
        self.topCheckBox.setObjectName(_fromUtf8("topCheckBox"))
        self.verticalLayout_2.addWidget(self.topCheckBox)
        self.gridLayout_2.addWidget(self.behaviourGroupBox, 0, 2, 1, 1)
        self.colorGroupBox = QtGui.QGroupBox(self.optionsGroupBox)
        self.colorGroupBox.setObjectName(_fromUtf8("colorGroupBox"))
        self.gridLayout = QtGui.QGridLayout(self.colorGroupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lineLabel = QtGui.QLabel(self.colorGroupBox)
        self.lineLabel.setObjectName(_fromUtf8("lineLabel"))
        self.gridLayout.addWidget(self.lineLabel, 0, 0, 1, 1)
        self.lineColorWidget = QtGui.QWidget(self.colorGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineColorWidget.sizePolicy().hasHeightForWidth())
        self.lineColorWidget.setSizePolicy(sizePolicy)
        self.lineColorWidget.setMinimumSize(QtCore.QSize(25, 0))
        self.lineColorWidget.setStyleSheet(_fromUtf8("background-color: black "))
        self.lineColorWidget.setObjectName(_fromUtf8("lineColorWidget"))
        self.gridLayout.addWidget(self.lineColorWidget, 0, 1, 1, 1)
        self.lineToolButton = QtGui.QToolButton(self.colorGroupBox)
        self.lineToolButton.setObjectName(_fromUtf8("lineToolButton"))
        self.gridLayout.addWidget(self.lineToolButton, 0, 2, 1, 1)
        self.cameraFrameColorWidget = QtGui.QWidget(self.colorGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameraFrameColorWidget.sizePolicy().hasHeightForWidth())
        self.cameraFrameColorWidget.setSizePolicy(sizePolicy)
        self.cameraFrameColorWidget.setMinimumSize(QtCore.QSize(25, 0))
        self.cameraFrameColorWidget.setStyleSheet(_fromUtf8("background-color: red"))
        self.cameraFrameColorWidget.setObjectName(_fromUtf8("cameraFrameColorWidget"))
        self.gridLayout.addWidget(self.cameraFrameColorWidget, 2, 1, 1, 1)
        self.backgroundLabel = QtGui.QLabel(self.colorGroupBox)
        self.backgroundLabel.setObjectName(_fromUtf8("backgroundLabel"))
        self.gridLayout.addWidget(self.backgroundLabel, 1, 0, 1, 1)
        self.cameraFrameLabel = QtGui.QLabel(self.colorGroupBox)
        self.cameraFrameLabel.setObjectName(_fromUtf8("cameraFrameLabel"))
        self.gridLayout.addWidget(self.cameraFrameLabel, 2, 0, 1, 1)
        self.backgroundToolButton = QtGui.QToolButton(self.colorGroupBox)
        self.backgroundToolButton.setObjectName(_fromUtf8("backgroundToolButton"))
        self.gridLayout.addWidget(self.backgroundToolButton, 1, 2, 1, 1)
        self.cameraFrameToolButton = QtGui.QToolButton(self.colorGroupBox)
        self.cameraFrameToolButton.setObjectName(_fromUtf8("cameraFrameToolButton"))
        self.gridLayout.addWidget(self.cameraFrameToolButton, 2, 2, 1, 1)
        self.markerLabel = QtGui.QLabel(self.colorGroupBox)
        self.markerLabel.setObjectName(_fromUtf8("markerLabel"))
        self.gridLayout.addWidget(self.markerLabel, 3, 0, 1, 1)
        self.markerComboBox = QtGui.QComboBox(self.colorGroupBox)
        self.markerComboBox.setMinimumSize(QtCore.QSize(125, 0))
        self.markerComboBox.setObjectName(_fromUtf8("markerComboBox"))
        self.markerComboBox.addItem(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/diamond.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerComboBox.addItem(icon1, _fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/scissor.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerComboBox.addItem(icon2, _fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/triangle.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markerComboBox.addItem(icon3, _fromUtf8(""))
        self.gridLayout.addWidget(self.markerComboBox, 3, 1, 1, 1)
        self.backgroundColorWidget = QtGui.QWidget(self.colorGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backgroundColorWidget.sizePolicy().hasHeightForWidth())
        self.backgroundColorWidget.setSizePolicy(sizePolicy)
        self.backgroundColorWidget.setMinimumSize(QtCore.QSize(25, 0))
        self.backgroundColorWidget.setStyleSheet(_fromUtf8("background-color: white"))
        self.backgroundColorWidget.setObjectName(_fromUtf8("backgroundColorWidget"))
        self.gridLayout.addWidget(self.backgroundColorWidget, 1, 1, 1, 1)
        self.transparentCheckBox = QtGui.QCheckBox(self.colorGroupBox)
        self.transparentCheckBox.setObjectName(_fromUtf8("transparentCheckBox"))
        self.gridLayout.addWidget(self.transparentCheckBox, 1, 3, 1, 1)
        self.objectLineCheckBox = QtGui.QCheckBox(self.colorGroupBox)
        self.objectLineCheckBox.setObjectName(_fromUtf8("objectLineCheckBox"))
        self.gridLayout.addWidget(self.objectLineCheckBox, 0, 3, 1, 1)
        self.gridLayout_2.addWidget(self.colorGroupBox, 0, 3, 1, 1)
        self.canvasGroupBox = QtGui.QGroupBox(self.optionsGroupBox)
        self.canvasGroupBox.setObjectName(_fromUtf8("canvasGroupBox"))
        self.formLayout_2 = QtGui.QFormLayout(self.canvasGroupBox)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.heightLabel = QtGui.QLabel(self.canvasGroupBox)
        self.heightLabel.setObjectName(_fromUtf8("heightLabel"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.heightLabel)
        self.heightSpinBox = QtGui.QSpinBox(self.canvasGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heightSpinBox.sizePolicy().hasHeightForWidth())
        self.heightSpinBox.setSizePolicy(sizePolicy)
        self.heightSpinBox.setMinimum(1)
        self.heightSpinBox.setMaximum(1920)
        self.heightSpinBox.setProperty("value", 480)
        self.heightSpinBox.setObjectName(_fromUtf8("heightSpinBox"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.heightSpinBox)
        self.widthLabel = QtGui.QLabel(self.canvasGroupBox)
        self.widthLabel.setObjectName(_fromUtf8("widthLabel"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.widthLabel)
        self.widthSpinBox = QtGui.QSpinBox(self.canvasGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widthSpinBox.sizePolicy().hasHeightForWidth())
        self.widthSpinBox.setSizePolicy(sizePolicy)
        self.widthSpinBox.setMinimum(1)
        self.widthSpinBox.setMaximum(2560)
        self.widthSpinBox.setProperty("value", 640)
        self.widthSpinBox.setObjectName(_fromUtf8("widthSpinBox"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.widthSpinBox)
        self.gridLayout_2.addWidget(self.canvasGroupBox, 1, 2, 1, 1)
        self.othersGroupBox = QtGui.QGroupBox(self.optionsGroupBox)
        self.othersGroupBox.setObjectName(_fromUtf8("othersGroupBox"))
        self.formLayout_3 = QtGui.QFormLayout(self.othersGroupBox)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.zoomLabel = QtGui.QLabel(self.othersGroupBox)
        self.zoomLabel.setObjectName(_fromUtf8("zoomLabel"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.zoomLabel)
        self.zoomSpinBox = QtGui.QSpinBox(self.othersGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomSpinBox.sizePolicy().hasHeightForWidth())
        self.zoomSpinBox.setSizePolicy(sizePolicy)
        self.zoomSpinBox.setMinimum(1)
        self.zoomSpinBox.setMaximum(10)
        self.zoomSpinBox.setProperty("value", 6)
        self.zoomSpinBox.setObjectName(_fromUtf8("zoomSpinBox"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.zoomSpinBox)
        self.folderNameLabel = QtGui.QLabel(self.othersGroupBox)
        self.folderNameLabel.setObjectName(_fromUtf8("folderNameLabel"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.folderNameLabel)
        self.folderNameLineEdit = QtGui.QLineEdit(self.othersGroupBox)
        self.folderNameLineEdit.setObjectName(_fromUtf8("folderNameLineEdit"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.folderNameLineEdit)
        self.gridLayout_2.addWidget(self.othersGroupBox, 1, 3, 1, 1)
        self.buildPathGroupBox = QtGui.QGroupBox(self.optionsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buildPathGroupBox.sizePolicy().hasHeightForWidth())
        self.buildPathGroupBox.setSizePolicy(sizePolicy)
        self.buildPathGroupBox.setObjectName(_fromUtf8("buildPathGroupBox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.buildPathGroupBox)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.fullPathCheckBox = QtGui.QCheckBox(self.buildPathGroupBox)
        self.fullPathCheckBox.setObjectName(_fromUtf8("fullPathCheckBox"))
        self.verticalLayout_4.addWidget(self.fullPathCheckBox)
        self.fillPathCheckBox = QtGui.QCheckBox(self.buildPathGroupBox)
        self.fillPathCheckBox.setObjectName(_fromUtf8("fillPathCheckBox"))
        self.verticalLayout_4.addWidget(self.fillPathCheckBox)
        self.circlePathCheckBox = QtGui.QCheckBox(self.buildPathGroupBox)
        self.circlePathCheckBox.setObjectName(_fromUtf8("circlePathCheckBox"))
        self.verticalLayout_4.addWidget(self.circlePathCheckBox)
        self.closePathCheckBox = QtGui.QCheckBox(self.buildPathGroupBox)
        self.closePathCheckBox.setEnabled(False)
        self.closePathCheckBox.setObjectName(_fromUtf8("closePathCheckBox"))
        self.verticalLayout_4.addWidget(self.closePathCheckBox)
        self.gridLayout_2.addWidget(self.buildPathGroupBox, 0, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.optionsGroupBox)
        self.chooseFileGroupBox = QtGui.QGroupBox(self.centralWidget)
        self.chooseFileGroupBox.setObjectName(_fromUtf8("chooseFileGroupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.chooseFileGroupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.openFileLineEdit = QtGui.QLineEdit(self.chooseFileGroupBox)
        self.openFileLineEdit.setReadOnly(True)
        self.openFileLineEdit.setObjectName(_fromUtf8("openFileLineEdit"))
        self.horizontalLayout.addWidget(self.openFileLineEdit)
        self.openFilePushButton = QtGui.QPushButton(self.chooseFileGroupBox)
        self.openFilePushButton.setObjectName(_fromUtf8("openFilePushButton"))
        self.horizontalLayout.addWidget(self.openFilePushButton)
        self.verticalLayout_3.addWidget(self.chooseFileGroupBox)
        self.buildPushButton = QtGui.QPushButton(self.centralWidget)
        self.buildPushButton.setObjectName(_fromUtf8("buildPushButton"))
        self.verticalLayout_3.addWidget(self.buildPushButton)
        self.outputTextEdit = QtGui.QTextEdit(self.centralWidget)
        self.outputTextEdit.setReadOnly(True)
        self.outputTextEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.outputTextEdit.setObjectName(_fromUtf8("outputTextEdit"))
        self.verticalLayout_3.addWidget(self.outputTextEdit)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1000, 25))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuMenu = QtGui.QMenu(self.menuBar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionSetting = QtGui.QAction(MainWindow)
        self.actionSetting.setObjectName(_fromUtf8("actionSetting"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionSVGBuild_Help = QtGui.QAction(MainWindow)
        self.actionSVGBuild_Help.setObjectName(_fromUtf8("actionSVGBuild_Help"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuMenu.addAction(self.actionSetting)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionSVGBuild_Help)
        self.menuHelp.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuMenu.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.buildPathCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.buildPathGroupBox.setEnabled)
        QtCore.QObject.connect(self.objectLineCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lineToolButton.setDisabled)
        QtCore.QObject.connect(self.transparentCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.backgroundToolButton.setDisabled)
        QtCore.QObject.connect(self.circlePathCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.closePathCheckBox.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "SVG Build", None, QtGui.QApplication.UnicodeUTF8))
        self.optionsGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.buildGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Build", None, QtGui.QApplication.UnicodeUTF8))
        self.buildPathCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.buildTextCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Text", None, QtGui.QApplication.UnicodeUTF8))
        self.buildImageCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Image", None, QtGui.QApplication.UnicodeUTF8))
        self.rangeGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Range", None, QtGui.QApplication.UnicodeUTF8))
        self.fromLabel.setText(QtGui.QApplication.translate("MainWindow", "From", None, QtGui.QApplication.UnicodeUTF8))
        self.untilLabel.setText(QtGui.QApplication.translate("MainWindow", "Until", None, QtGui.QApplication.UnicodeUTF8))
        self.behaviourGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Behaviour", None, QtGui.QApplication.UnicodeUTF8))
        self.pageCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Page", None, QtGui.QApplication.UnicodeUTF8))
        self.cameraCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.backwardCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Backward", None, QtGui.QApplication.UnicodeUTF8))
        self.topCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Top", None, QtGui.QApplication.UnicodeUTF8))
        self.colorGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.lineLabel.setText(QtGui.QApplication.translate("MainWindow", "Line", None, QtGui.QApplication.UnicodeUTF8))
        self.lineToolButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.backgroundLabel.setText(QtGui.QApplication.translate("MainWindow", "Background", None, QtGui.QApplication.UnicodeUTF8))
        self.cameraFrameLabel.setText(QtGui.QApplication.translate("MainWindow", "Camera Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.backgroundToolButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.cameraFrameToolButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.markerLabel.setText(QtGui.QApplication.translate("MainWindow", "Marker", None, QtGui.QApplication.UnicodeUTF8))
        self.markerComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.markerComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Diamond", None, QtGui.QApplication.UnicodeUTF8))
        self.markerComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Scissor", None, QtGui.QApplication.UnicodeUTF8))
        self.markerComboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "Triangle", None, QtGui.QApplication.UnicodeUTF8))
        self.transparentCheckBox.setText(QtGui.QApplication.translate("MainWindow", "transparent", None, QtGui.QApplication.UnicodeUTF8))
        self.objectLineCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Object\'s Line", None, QtGui.QApplication.UnicodeUTF8))
        self.canvasGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Canvas", None, QtGui.QApplication.UnicodeUTF8))
        self.heightLabel.setText(QtGui.QApplication.translate("MainWindow", "Height", None, QtGui.QApplication.UnicodeUTF8))
        self.widthLabel.setText(QtGui.QApplication.translate("MainWindow", "Width", None, QtGui.QApplication.UnicodeUTF8))
        self.othersGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Others", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomLabel.setText(QtGui.QApplication.translate("MainWindow", "Zoom", None, QtGui.QApplication.UnicodeUTF8))
        self.folderNameLabel.setText(QtGui.QApplication.translate("MainWindow", "Folder Name", None, QtGui.QApplication.UnicodeUTF8))
        self.folderNameLineEdit.setText(QtGui.QApplication.translate("MainWindow", "movie", None, QtGui.QApplication.UnicodeUTF8))
        self.buildPathGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Build Path", None, QtGui.QApplication.UnicodeUTF8))
        self.fullPathCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Full Path", None, QtGui.QApplication.UnicodeUTF8))
        self.fillPathCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Fill Path", None, QtGui.QApplication.UnicodeUTF8))
        self.circlePathCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Circle Path", None, QtGui.QApplication.UnicodeUTF8))
        self.closePathCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Close Path", None, QtGui.QApplication.UnicodeUTF8))
        self.chooseFileGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Choose File", None, QtGui.QApplication.UnicodeUTF8))
        self.openFilePushButton.setText(QtGui.QApplication.translate("MainWindow", "Open file", None, QtGui.QApplication.UnicodeUTF8))
        self.buildPushButton.setText(QtGui.QApplication.translate("MainWindow", "Build!", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMenu.setTitle(QtGui.QApplication.translate("MainWindow", "&Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSetting.setText(QtGui.QApplication.translate("MainWindow", "&Setting", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "E&xit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSVGBuild_Help.setText(QtGui.QApplication.translate("MainWindow", "SVGBuild &Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "&About", None, QtGui.QApplication.UnicodeUTF8))

import resource_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

